image:
  file: .gitpod.Dockerfile

tasks:
  - name: Aufgabe 3
    init: javac Spieler.java
    command: java Spieler
  - name: Aufgabe 5
    init: javac TestRectangles.java
    command: java TestRectangles
  - name: Javadoc
    command: javadoc -d doc Rectangle.java
  - name: Javadoc Server
    command: |
      cd doc
      python3 -m http.server 3000

vscode:
  extensions:
    - vscjava.vscode-java-pack
