tasks:
  - name: Install Java 17
    init: |
      sdk install java 17.0.1-open
      sdk default java 17.0.1-open
  - name: run
    init: javac 
    command: java 

vscode:
  extensions:
    - vscjava.vscode-java-pack
