image:
  file: .gitpod.Dockerfile

tasks:
  - name: Aufgabe 3
    init: javac Spieler.java
    command: java Spieler
  - name: Aufgabe 5
    init: javac TestRectangles.java
    command: java TestRectangles

vscode:
  extensions:
    - vscjava.vscode-java-pack
